services:
  project-kaizen-postgres:
    image: postgres:17
    container_name: project-kaizen-db
    environment:
      POSTGRES_DB: kz_knowledge
      POSTGRES_USER: kz_user
      POSTGRES_PASSWORD: kz_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5453:5432"
    volumes:
      - kz_data:/var/lib/postgresql/data/pgdata
      - ./01-initial-schema.sql:/docker-entrypoint-initdb.d/01-initial-schema.sql
      - ./test/sample-data.sql:/docker-entrypoint-initdb.d/02-sample-data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kz_user -d kz_knowledge"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  project-kaizen-mcp:
    build:
      context: ../mcp-server
      dockerfile: Dockerfile
    container_name: project-kaizen-mcp
    environment:
      POSTGRES_URL: "postgresql://kz_user:kz_password@project-kaizen-postgres:5432/kz_knowledge"
    depends_on:
      project-kaizen-postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  kz_data:
    driver: local
